In [2]:
#task 1
import pandas as pd
import numpy as np
s1=pd.Series(np.random.rand(4))
s2=pd.Series(np.random.rand(4))
s3=pd.Series(np.random.rand(4))
s4=pd.Series(np.random.rand(4))
print(s1,s2,s3,s4)
df=pd.DataFrame([s1,s2,s3,s4])
df

0    0.785235
1    0.936931
2    0.003579
3    0.137113
dtype: float64 0    0.965027
1    0.833018
2    0.701488
3    0.145581
dtype: float64 0    0.219004
1    0.195952
2    0.478540
3    0.069883
dtype: float64 0    0.020550
1    0.640598
2    0.097762
3    0.353830
dtype: float64

          0         1         2         3
0  0.785235  0.936931  0.003579  0.137113
1  0.965027  0.833018  0.701488  0.145581
2  0.219004  0.195952  0.478540  0.069883
3  0.020550  0.640598  0.097762  0.353830

In [3]:
#task 2
df.columns=['Random value 1','Random value 2','Random value 3','Random value 4']
df

   Random value 1  Random value 2  Random value 3  Random value 4
0        0.785235        0.936931        0.003579        0.137113
1        0.965027        0.833018        0.701488        0.145581
2        0.219004        0.195952        0.478540        0.069883
3        0.020550        0.640598        0.097762        0.353830

In [4]:
#task 3
df.describe() #numeric

       Random value 1  Random value 2  Random value 3  Random value 4
count        4.000000        4.000000        4.000000        4.000000
mean         0.497454        0.651625        0.320342        0.176602
std          0.449598        0.327649        0.326690        0.122909
min          0.020550        0.195952        0.003579        0.069883
25%          0.169390        0.529436        0.074216        0.120306
50%          0.502119        0.736808        0.288151        0.141347
75%          0.830183        0.858996        0.534277        0.197644
max          0.965027        0.936931        0.701488        0.353830

In [5]:
#task 3
df.describe(include='all') #string

       Random value 1  Random value 2  Random value 3  Random value 4
count        4.000000        4.000000        4.000000        4.000000
mean         0.497454        0.651625        0.320342        0.176602
std          0.449598        0.327649        0.326690        0.122909
min          0.020550        0.195952        0.003579        0.069883
25%          0.169390        0.529436        0.074216        0.120306
50%          0.502119        0.736808        0.288151        0.141347
75%          0.830183        0.858996        0.534277        0.197644
max          0.965027        0.936931        0.701488        0.353830

In [7]:
#task 4
df.isnull().sum() #numeric

Random value 1    0
Random value 2    0
Random value 3    0
Random value 4    0
dtype: int64

In [8]:
#task 4
df.isnull()#boolean

   Random value 1  Random value 2  Random value 3  Random value 4
0           False           False           False           False
1           False           False           False           False
2           False           False           False           False
3           False           False           False           False

In [12]:
#task 4
print('column1 datatype is',df['Random value 1'].dtype)
print('column2 datatype is',df['Random value 2'].dtype)
print('column3 datatype is',df['Random value 3'].dtype)
print('column4 datatype is',df['Random value 4'].dtype)

column1 datatype is float64
column2 datatype is float64
column3 datatype is float64
column4 datatype is float64

In [16]:
#task 5
df.loc[0:4,'Random value 2':'Random value 3'] #location method

   Random value 2  Random value 3
0        0.936931        0.003579
1        0.833018        0.701488
2        0.195952        0.478540
3        0.640598        0.097762

In [19]:
#task 5
df.iloc[0:,1:3] #index location(0:index location elements,1:3 column range)

   Random value 2  Random value 3
0        0.936931        0.003579
1        0.833018        0.701488
2        0.195952        0.478540
3        0.640598        0.097762